include $(GNUSTEP_MAKEFILES)/common.make
OBJCFLAGS = -fobjc-arc
LDFLAGS = -ldispatch
APP_NAME = class_fraction 
class_fraction_OBJC_FILES = class_fraction.m
include $(GNUSTEP_MAKEFILES)/application.make
